# Generated by Django 5.1.15 on 2026-10-02 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='last_corrected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近更正时间'),
        ),
        migrations.AddField(
            model_name='issue',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='投影版本'),
        ),
        migrations.CreateModel(
            name='CorrectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='更正原因')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('applied', '已应用'), ('withdrawn', '已撤回')], db_index=True, default='draft', max_length=10, verbose_name='状态')),
                ('client_ref', models.CharField(blank=True, max_length=64, verbose_name='客户端幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='应用时间')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='serials.title')),
            ],
            options={
                'verbose_name': '发行更正单',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_before', models.CharField(choices=[('regular', '普通期'), ('combined', '合刊')], max_length=10, verbose_name='原类型')),
                ('kind_after', models.CharField(choices=[('regular', '普通期'), ('combined', '合刊')], max_length=10, verbose_name='拟议类型')),
                ('month_start_before', models.DateField(verbose_name='原发行起始月')),
                ('month_end_before', models.DateField(blank=True, null=True, verbose_name='原发行截止月')),
                ('month_start_after', models.DateField(verbose_name='拟议发行起始月')),
                ('month_end_after', models.DateField(blank=True, null=True, verbose_name='拟议发行截止月')),
                ('version_before', models.PositiveIntegerField(blank=True, null=True, verbose_name='应用前版本')),
                ('version_after', models.PositiveIntegerField(blank=True, null=True, verbose_name='应用后版本')),
                ('issue', models.ForeignKey(help_text='更正只投影编号与发行区间，发行实体本身不变（实物/装订不断链）', on_delete=django.db.models.deletion.PROTECT, related_name='correction_lines', to='serials.issue')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='serials.correctionorder')),
            ],
            options={
                'verbose_name': '更正行',
            },
        ),
        migrations.CreateModel(
            name='CorrectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '开单'), ('update', '改单'), ('apply', '应用'), ('apply_replay', '重复应用（幂等）'), ('withdraw', '撤回'), ('withdraw_replay', '重复撤回（幂等）'), ('reject', '拒绝')], max_length=20, verbose_name='动作')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='serials.correctionorder')),
            ],
            options={
                'verbose_name': '更正审计事件',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_version', models.PositiveIntegerField(verbose_name='导出时发行期版本')),
                ('barcode', models.CharField(blank=True, max_length=40, verbose_name='条码（快照）')),
                ('month_start', models.DateField(verbose_name='发行起始月（快照）')),
                ('month_end', models.DateField(blank=True, null=True, verbose_name='发行截止月（快照）')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='实际位置（快照）')),
                ('numbers_json', models.JSONField(default=list, verbose_name='期号关系（快照）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='serials.issue')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='serials.item')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='serials.title')),
            ],
            options={
                'verbose_name': '导出快照',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionNumberSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('before', '原覆盖'), ('after', '拟议覆盖')], max_length=10, verbose_name='快照侧')),
                ('volume', models.CharField(blank=True, max_length=20, verbose_name='卷（快照）')),
                ('number_label', models.CharField(max_length=20, verbose_name='期（快照）')),
                ('cover_label', models.CharField(blank=True, max_length=40, verbose_name='封面标识（快照）')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_snapshots', to='serials.correctionline')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_snapshots', to='serials.issuenumber')),
            ],
            options={
                'verbose_name': '编号关联快照',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['side'], name='serials_cor_side_4a5fc9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='correctionorder',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref', ''), _negated=True), fields=('title', 'client_ref'), name='uniq_correction_client_ref_per_title'),
        ),
        migrations.AddConstraint(
            model_name='correctionline',
            constraint=models.UniqueConstraint(fields=('order', 'issue'), name='uniq_line_issue_per_order'),
        ),
    ]
