# Generated by Django 5.1.15 on 2026-10-02 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='coverage_version',
            field=models.PositiveIntegerField(default=1, verbose_name='覆盖版本'),
        ),
        migrations.CreateModel(
            name='IssueCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('applied', '已应用'), ('withdrawn', '已撤回')], default='draft', max_length=10, verbose_name='状态')),
                ('reason', models.CharField(max_length=255, verbose_name='更正原因')),
                ('proposed_issue_month', models.DateField(verbose_name='拟议发行年月')),
                ('proposed_issue_month_end', models.DateField(blank=True, null=True, verbose_name='拟议发行截止年月')),
                ('original_numbers', models.JSONField(default=list, help_text='[{number_id, volume, number, label}, ...]', verbose_name='原覆盖编号快照')),
                ('original_issue_month', models.DateField(blank=True, null=True, verbose_name='原发行年月')),
                ('original_issue_month_end', models.DateField(blank=True, null=True, verbose_name='原发行截止年月')),
                ('applied_issue_version', models.PositiveIntegerField(blank=True, help_text='本次更正应用后 Issue 的 coverage_version', null=True, verbose_name='应用时版本')),
                ('withdrawn_issue_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='撤回后版本')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='更正单版本')),
                ('client_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='幂等令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(help_text='被更正的发行实体；实体身份与装订/条码关系不随更正改变', on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='serials.issue')),
            ],
            options={
                'verbose_name': '发行更正单',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_version', models.PositiveIntegerField(verbose_name='导出时覆盖版本')),
                ('snapshot', models.JSONField(default=dict, verbose_name='覆盖关系快照')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_records', to='serials.issue')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='serials.title')),
                ('correction', models.ForeignKey(blank=True, help_text='导出时生效的更正单（无则为原始发行关系）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_records', to='serials.issuecorrection')),
            ],
            options={
                'verbose_name': '导出记录',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_label', models.CharField(blank=True, max_length=40, verbose_name='拟议封面标识')),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='行序')),
                ('original_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_original_lines', to='serials.issuenumber')),
                ('proposed_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_proposed_lines', to='serials.issuenumber')),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='serials.issuecorrection')),
            ],
            options={
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建草稿'), ('update', '修改草稿'), ('apply', '应用'), ('reapply', '重复应用（幂等）'), ('withdraw', '撤回'), ('rewithdraw', '重复撤回（幂等）'), ('reject', '乱序/冲突拒绝')], max_length=12)),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('expected_version', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_version_after', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='serials.issuecorrection')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='issuecorrection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('issue',), name='uniq_draft_correction_per_issue'),
        ),
    ]
